certifiedapp/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from certifiedapp import views as core_views

urlpatterns =[
    # url(r'^login/$', auth_views.login,  name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login/'}, name="logout"),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^change_password/$', core_views.change_password, name="change_password"),
    url(r'^userdashbord/$', core_views.userdashbord, name='userdashbord'),
    url(r'^Test_List/$',core_views.test_list,name='Testlist'),
    url(r'^Take_Predict/$',core_views.takepredict,name='Takepredict'),
    url(r'^charts/simple.png$', core_views.simple),
    url(r'^forgot_password/$', core_views.forgot_password, name="forgot_password"),
    url(r'^upload/csv/$', core_views.upload_csv, name='upload_csv'),
    url(r'^student_freetest/$', core_views.student_freetest, name='student_freetest'),
    url(r'^student_test_submit/$', core_views.student_test_submit, name='student_test_submit'),
    url(r'^student_testresult/$', core_views.student_testresult, name='student_testresult'),
    url(r'forget_password_reset/',core_views.forget_password_reset , name='forget_password_reset'),
]

hc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
# from hc.accounts.views import login as hc_login
# import bugtrackapp
from bugtrackapp.views import rschome as home

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # url(r'^admin/login/', hc_login, {"show_password": True}),
    url(r'^admin/', admin.site.urls),
    url(r'^$',home),
    url(r'login/$', auth_views.login, {'template_name': 'registration/cert_app_login.html'} ,name='login'),

    url(r'^', include('bugtrackapp.urls', namespace="bugtrackapp")),
    url(r'^', include('certifiedapp.urls',namespace="certifiedapp")),
    url(r'^', include('subjectsapp.urls',namespace="subjectapp")),
    url(r'^', include('toolsapp.urls',namespace="toolsapp")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Author(models.Model):
    name = models.CharField(max_length=64)
    email = models.CharField(max_length=64)

    def __str__(self):
        return "%s (%s)" % (self.name, self.email)

category_choices = (('PY','Python'),('ML','Machine Learning'),('MLWPY','Machine Learning with Python'),('FAQ','FAQ'),)

class Post(models.Model):
    title = models.CharField(max_length=64)
    date = models.DateTimeField()
    author = models.ForeignKey(Author)
    body = models.TextField()
    description = models.CharField(max_length=50, default="None")
    summary = models.CharField(max_length=300 , default="None")
    post_image = models.ImageField(upload_to='blogimg/', default="Null")
    document = models.FileField(upload_to='blogimg/', default="Null")
    category = models.CharField(max_length=255,default='ML',choices=category_choices)

    def __str__(self):
        return "%s (%s)" % (self.title, self.author.name)


class PostComment(models.Model):
    comment = models.TextField()
    post_id =models.ForeignKey(Post)
    user_name =  models.ForeignKey(User)
    date = models.DateTimeField()

templates/accounts/Change_password.html
{% block content %}
{%include 'header.html'%}
{% load static %}
<!-- the code add for slider-->
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->



<div class="container">
            <div id="passwordreset" style="margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <div class="panel-title">Change Password</div>
                    </div>
                    <div class="panel-body">
 <form method="post" action="{% url 'certifiedapp:change_password' %}">
    {% csrf_token %}


                            <div class="form-group">
                                <div class="col-md-12">

    {% for i in form %}
      <b> {{i.label}}:<br> </b>
       {{i}}<br><br>

         {%endfor%}


                                </div>
                            </div>
                            <div class="form-group">
                                <!-- Button -->
                                <div class="  col-sm-offset-5 col-sm-7">
                                    <button id="btn-signup" type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

<br>
<br>


</div>
</div>



{%include 'footer.html'%}
{%include 'script_style.html'%}
{% endblock %}

templates/accounts/badges.html
{% extends "base.html" %}
{% load compress staticfiles hc_extras %}

{% block title %}Account Settings - {% site_name %}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h1 class="settings-title">Settings</h1>
    </div>
</div>

<div class="row">
    <div class="col-sm-2">
        <ul class="nav nav-pills nav-stacked">
            <li><a href="{% url 'hc-profile' %}">Account</a></li>
            <li><a href="{% url 'hc-notifications' %}">Email Reports</a></li>
            <li class="active"><a href="{% url 'hc-badges' %}">Badges</a></li>
        </ul>
    </div>

    <div class="col-sm-10">
        <div class="panel panel-default">
            <div class="panel-body settings-block">
                <h2 class="settings-title">Status Badges</h2>
                <p id="badges-description">
                    healthchecks.io provides status badges for each of the tags
                    you have used. The badges have public, but hard-to-guess
                    URLs. If you wish, you can add them to your READMEs,
                    dashboards or status pages.
                </p>

                <div id="b-format" class="btn-group" data-toggle="buttons">
                    <label id="show-svg" class="btn btn-default active">
                        <input type="radio" autocomplete="off" checked> SVG
                    </label>
                    <label id="show-json" class="btn btn-default">
                        <input type="radio" autocomplete="off"> JSON
                    </label>
                </div>

                <table id="badges-svg" class="badges table">
                    {% for urldict in urls %}
                    <tr>
                        <td>
                            <img src="{{ urldict.svg }}" alt="" />
                        </td>
                        <td class="svg-url">
                            <code>{{ urldict.svg }}</code>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td class="overall-status {% if urls %}have-tags{% endif %}" colspan="2">Overall status:</td>
                    </tr>
                    <tr>
                        <td>
                            <img src="{{ master.svg }}" alt="" />
                        </td>
                        <td class="svg-url">
                            <code>{{ master.svg }}</code>
                        </td>
                    </tr>
                </table>
                <table id="badges-json" class="badges table">
                    {% for urldict in urls %}
                    <tr>
                        <td class="json-response" data-url="{{ urldict.json }}">
                        </td>
                        <td class="json-url">
                            <code>{{ urldict.json }}</code>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td class="overall-status {% if urls %}have-tags{% endif %}"" colspan="2">Overall status:</td>
                    </tr>
                    <tr>
                        <td class="json-response" data-url="{{ master.json }}">
                        <td class="json-url">
                            <code>{{ master.json }}</code>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% compress js %}
<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/badges.js' %}"></script>
{% endcompress %}
{% endblock %}

templates/accounts/change_email.html
{% extends "base.html" %}
{% load hc_extras %}

{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="hc-dialog">
            <h1>Change Account's Email Address</h1>
            <div class="dialog-body">
                <p>
                    Your account's email address is used for sending
                    the sign-in links and monthly reports.

                    <strong>
                        Make sure you can receive emails at the new address.
                    </strong>

                    Otherwise, you may get locked out of
                    your {% site_name %} account.
                </p>

                {% if request.user.has_usable_password %}
                <p>
                    Note: Changing the email address will also
                    <strong>reset your current password</strong>
                    and log you out.
                </p>
                {% endif %}
            </div>

            <form class="form-horizontal" method="post">
                {% csrf_token %}

                <div class="form-group">
                    <label class="col-sm-3 control-label">Current Email</label>
                    <div class="col-sm-9">
                        <input
                            type="text"
                            class="form-control"
                            disabled
                            value="{{ request.user.email }}">
                    </div>
                </div>

                <div class="form-group {{ form.email.css_classes }}">
                    <label for="ce-email" class="col-sm-3 control-label">New Email</label>
                    <div class="col-sm-9">
                        <input
                            type="email"
                            class="form-control"
                            id="ce-email"
                            name="email"
                            placeholder="you@example.org">
                            {% if form.email.errors %}
                            <div class="help-block">
                                {{ form.email.errors|join:"" }}
                            </div>
                            {% endif %}

                    </div>
                </div>

                <div class="clearfix">
                    <button type="submit" class="btn btn-lg btn-primary pull-right">
                        Change Email
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/change_email_done.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="hc-dialog">
            <h1>Email Address Updated</h1>
            <br />
            <p>
                Your account's email address has been updated.
                You can now <a href="{% url 'hc-login' %}">sign in</a>
                with the new email address.
            </p>
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/check_token_submit.html
{% load hc_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Continue to {% site_name %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<form id="form-auto" method="post">{% csrf_token %}</form>
<script>
    document.getElementById("form-auto").submit();
</script>

<style>
    body {
        font-family: Arial;
        text-align: center;
        margin: 10em;
    }

    input {
        display: inline-block;
        margin-bottom: 0;
        font-weight: normal;
        text-align: center;
        vertical-align: middle;
        touch-action: manipulation;
        cursor: pointer;
        background-image: none;
        border: 1px solid transparent;
        white-space: nowrap;
        padding: 10px 16px;
        font-size: 18px;
        line-height: 1.3333333;
        border-radius: 6px;
        color: #ffffff;
        background-color: #22bc66;
        border-color: #1ea65a;
    }
</style>

<noscript>
    <p>You are about to log into {% site_name %}.</p>
    <p>Please press the button below to continue:</p>
    <br />
    <form id="form" method="post">
        {% csrf_token %}
        <input
            id="submit-btn"
            type="submit"
            class="btn btn-lg btn-primary"
            value="Continue to {% site_name %}">
    </form>
</noscript>

</body>
</html>

templates/accounts/link_sent.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="hc-dialog">
            <h1>Email with Instructions Sent!</h1>
            <br />
            <p>
                We've sent you an email with further instructions.
                Please check your inbox!
            </p>

        </div>
    </div>
</div>

{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}
{% load compress staticfiles %}

{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="hc-dialog">
            {% if bad_link %}
            <h1>Incorrect Login Link</h1>
            <div class="dialog-body">
                <p>The login link you just used is either incorrect or expired.</p>
                <p>Please use the form below to request a fresh login link:</p>
            </div>
            {% else %}
            <h1>Healthchecks</h1>
            <div class="dialog-body">
                <p>
                {% if show_password %}
                    Please enter your email address and password.
                {% else %}
                    Please enter your email address.
                    Next, we'll send you an email with log-in instructions!
                {% endif %}
                </p>
            </div>
            {% endif %}

            {% if bad_credentials %}
            <p class="alert alert-danger">Incorrect email or password.</p>
            {% endif %}

            <form method="post">
                {% csrf_token %}

                <div class="form-group">
                    <div class="input-group input-group-lg">
                        <div class="input-group-addon">
                            <span class="icon-mail"></span>
                        </div>
                        <input
                            type="text"
                            class="form-control"
                            id="id_email"
                            name="email"
                            value="{{ form.email.value|default:"" }}"
                            placeholder="Email">
                    </div>
                </div>

                {% if not show_password %}
                <div class="checkbox" id="password-toggle">
                    <label>
                        <input type="checkbox"> I want to use a password
                    </label>
                </div>
                {% endif %}


                <div id="password-block" class="form-group {% if not show_password %} hide {% endif %}">
                    <div class="input-group input-group-lg">
                        <div class="input-group-addon">
                            <span class="icon-dots"></span>
                        </div>
                        <input
                            type="password"
                            class="form-control"
                            name="password"
                            placeholder="password">
                    </div>
                </div>

                <div class="clearfix">
                    <button type="submit" class="btn btn-lg btn-primary pull-right">
                        Log In
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% compress js %}
<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'js/login.js' %}"></script>
{% endcompress %}
{% endblock %}

templates/accounts/login_link_sent.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="hc-dialog">
            <h1>Login Link Sent!</h1>
            <br />
            <p>
                We've sent you an email with login instructions.
                Please check your inbox!
            </p>

        </div>
    </div>
</div>

{% endblock %}

templates/accounts/notifications.html
{% extends "base.html" %}
{% load compress staticfiles hc_extras %}

{% block title %}Account Settings - {% site_name %}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h1 class="settings-title">Settings</h1>
    </div>
</div>

<div class="row">
    <div class="col-sm-3">
        <ul class="nav nav-pills nav-stacked">
            <li><a href="{% url 'hc-profile' %}">Account</a></li>
            <li class="active"><a href="{% url 'hc-notifications' %}">Email Reports</a></li>
            <li><a href="{% url 'hc-badges' %}">Badges</a></li>
        </ul>
    </div>

    <div class="col-sm-9 col-md-6">
        <div class="panel panel-{{ status }}">
            <div class="panel-body settings-block">
                <form method="post">
                    {% csrf_token %}
                    <h2>Email Reports</h2>

                    <p>Send me monthly emails about:</p>
                    <label class="checkbox-container">
                        <input
                            name="reports_allowed"
                            type="checkbox"
                            {% if profile.reports_allowed %} checked {% endif %}>
                        <span class="checkmark"></span>
                        The status of checks in all teams I belong to
                    </label>

                    <br>
                    <p>If any checks are down:</p>

                    <label class="radio-container">
                        <input
                            type="radio"
                            name="nag_period"
                            value="0"
                            {% if profile.nag_period.total_seconds == 0 %} checked {% endif %}>
                        <span class="radiomark"></span>
                        Do not remind me
                    </label>
                    <label class="radio-container">
                        <input
                            type="radio"
                            name="nag_period"
                            value="86400"
                            {% if profile.nag_period.total_seconds == 86400 %} checked {% endif %}>
                        <span class="radiomark"></span>
                        Remind me daily
                    </label>
                    <label class="radio-container">
                        <input
                            type="radio"
                            name="nag_period"
                            value="3600"
                            {% if profile.nag_period.total_seconds == 3600 %} checked {% endif %}>
                        <span class="radiomark"></span>
                        Remind me hourly
                    </label>

                    <br />
                    <p style="color: #888">
                        Reports will be delivered to {{ profile.user.email }}. <br />
                        {% if profile.next_report_date %}
                            Next monthly report date is
                            {{ profile.next_report_date.date }}.
                        {% endif %}
                    </p>
                    <br />


                    <button
                        name="update_reports_allowed"
                        type="submit"
                        class="btn btn-default pull-right">Save Changes</button>
                </form>
            </div>
            {% if status == "info" %}
            <div class="panel-footer">
                Your settings have been updated!
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% compress js %}
<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endcompress %}
{% endblock %}

templates/accounts/set_password.html
{% extends "base.html" %}
{% load hc_extras %}

{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="hc-dialog">
            <h1>Set a Password</h1>
            <div class="dialog-body">
                <p>
                    Please pick a password for your {% site_name %} account.
                </p>
            </div>

            <form method="post">
                {% csrf_token %}

                <div class="form-group">
                    <div class="input-group input-group-lg">
                        <div class="input-group-addon">
                            <span class="icon-dots"></span>
                        </div>
                        <input
                            type="password"
                            class="form-control"
                            name="password"
                            placeholder="pick a password">
                    </div>
                </div>

                <div class="clearfix">
                    <button type="submit" class="btn btn-lg btn-primary pull-right">
                        Set Password
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/unsubscribed.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="hc-dialog">
            <h1>You have been unsubscribed</h1>
        </div>
    </div>
</div>

{% endblock %}