certifiedapp/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from certifiedapp import views as core_views

urlpatterns =[
    # url(r'^login/$', auth_views.login,  name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login/'}, name="logout"),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^change_password/$', core_views.change_password, name="change_password"),
    url(r'^userdashbord/$', core_views.userdashbord, name='userdashbord'),
    url(r'^Test_List/$',core_views.test_list,name='Testlist'),
    url(r'^Take_Predict/$',core_views.takepredict,name='Takepredict'),
    url(r'^charts/simple.png$', core_views.simple),
    url(r'^forgot_password/$', core_views.forgot_password, name="forgot_password"),
    url(r'^upload/csv/$', core_views.upload_csv, name='upload_csv'),
    url(r'^student_freetest/$', core_views.student_freetest, name='student_freetest'),
    url(r'^student_test_submit/$', core_views.student_test_submit, name='student_test_submit'),
    url(r'^student_testresult/$', core_views.student_testresult, name='student_testresult'),
    url(r'forget_password_reset/',core_views.forget_password_reset , name='forget_password_reset'),
]

hc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
# from hc.accounts.views import login as hc_login
# import bugtrackapp
from bugtrackapp.views import rschome as home

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # url(r'^admin/login/', hc_login, {"show_password": True}),
    url(r'^admin/', admin.site.urls),
    url(r'^$',home),
    url(r'login/$', auth_views.login, {'template_name': 'registration/cert_app_login.html'} ,name='login'),

    url(r'^', include('bugtrackapp.urls', namespace="bugtrackapp")),
    url(r'^', include('certifiedapp.urls',namespace="certifiedapp")),
    url(r'^', include('subjectsapp.urls',namespace="subjectapp")),
    url(r'^', include('toolsapp.urls',namespace="toolsapp")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subjectsapp/urls.py
from django.conf.urls import include, url

from subjectsapp import views


urlpatterns =[
    url(r'^allsubjects/$', views.subjectlist, name="subjectlist"),
    url(r'^addsubject/$', views.add_subject, name="add_subject"),
    url(r'^editsubject/(?P<pk>\d+)$', views.edit_subject, name="editsubject"),
    url(r'^allpapers/$', views.paperslist, name="paperslist"),
    url(r'^addpapers/$', views.add_papers, name="add_papers"),
    url(r'^editpapertype/(?P<pk>\d+)$', views.edit_papertype, name="edit_papertype"),
    url(r'^allquestions/$', views.questionlist, name="questionlist"),
    url(r'^addquestions/$', views.add_questions, name="add_questions"),
    url(r'^editquestiontype/(?P<pk>\d+)$', views.edit_questions, name="edit_questions"),
    url(r'^results/$', views.results, name="results"),


]

certifiedapp/models.py
from django.db import models
from django.contrib.auth.models import *
from subjectsapp.models import Paperstype
from datetime import datetime
class Testlist(models.Model):
    tst_name = models.CharField(max_length=50,default="coming soon")
    

class Newuser(User):
    object = UserManager()

    class Meta:
        proxy = True
        verbose_name = "New user model"
        verbose_name_plural = "New user models"

    def __str__(self):
        return 'Username:{}, email:{},lastname: {}'.format(self.username,self.email,self.last_name)


class StudentResults(models.Model):
    stu_user = models.ForeignKey(User)
    total_marks = models.PositiveSmallIntegerField(default=0)
    total_question = models.PositiveSmallIntegerField(default=0)
    status = models.BooleanField(default=False)
    paper_type = models.ForeignKey(Paperstype)
    date_created = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return '{}'.format(self.stu_user, self.total_marks,self.paper_type)


class StudentProfile(models.Model):
    stu_user = models.OneToOneField(User)
    stu_photo = models.FileField(upload_to='stu_profiles/')
    stu_status = models.FileField(upload_to='stu_status/')

    def __str__(self):
        return '{0}'.format(self.stu_user)

certifiedapp/forms.py
from django.forms import * 

from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import StudentProfile
class UserCreationForm(UserCreationForm):
    email = EmailField(label=_("Email address"), required=True,
                               widget=TextInput(attrs={'class':'form-control','placeholder':'Email'}))
    username = CharField(widget=TextInput(attrs={'class':'form-control','placeholder':'Username'}))
    password1 = CharField(label="Password", widget=PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))
    password2 = CharField(label="Confirm Password", widget=PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return


class StudentProfileform(forms.ModelForm):
    class Meta:
        model = StudentProfile
        fields = ('stu_photo',)

certifiedapp/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, render_to_response
import random
import django
import datetime

# Create your views here.
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.messages import *
from django.contrib.auth.models import User
from subjectsapp.models import Questions,Paperstype
from certifiedapp.models import StudentResults
from bugtrackapp.views import *

def certifiedapphome(request):
    return HttpResponse('cerifiedapphome')


from django.contrib.auth import login, authenticate
# from django.contrib.auth.forms import
from certifiedapp.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth.forms import PasswordChangeForm
from .forms import StudentProfileform
from .models import StudentProfile
def forgot_password(request):
    return render(request,'forgot_password.html',context={})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'registration/certapp_signup.html', {'form': form})

@login_required
def studentprofilepic(request):
    # only for superuser..

    if request.method == 'POST':
        form = StudentProfileform(request.POST, request.FILES)
        if form.is_valid():
            picform = form.save(commit=False)
            picform.stu_user = request.user
            picform.save()


@login_required
def userdashbord(request):

    context = {}
    return render(request,'certifiedapp/userdashbord.html',context)



from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')

            return redirect('login')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/Change_password.html', {
        'form': form
    })


from django.contrib.auth import *
from certifiedapp.models import Testlist
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
def simple(request):
    import random
    import django
    import datetime
    from matplotlib.dates import DateFormatter

    fig=Figure()
    ax=fig.add_subplot(111)
    x=[]
    y=[]
    now=datetime.datetime.now()
    delta=datetime.timedelta(days=1)
    for i in range(10):
        x.append(now)
        now+=delta
        y.append(random.randint(0, 800))
    ax.plot_date(x, y, '-')
    ax.xaxis.set_major_formatter(DateFormatter('%Y-%m-%d'))
    fig.autofmt_xdate()
    canvas=FigureCanvas(fig)
    response=django.http.HttpResponse(content_type='image/png')
    canvas.print_png(response)
    return response

from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
def upload_csv(request):
    data = {}
    if "GET" == request.method:
        return render(request, "certifiedapp/Take_Test.html", data)
    # if not GET, then proceed
    else:
        csv_file = request.FILES["csv_file"]
        if not csv_file.name.endswith('.csv'):
            messages.error(request,'File is not CSV type')
            return HttpResponseRedirect(reverse("certifiedapp:upload_csv"))
        #if file is too large, return
        if csv_file.multiple_chunks():
            messages.error(request,"Uploaded file is too big (%.2f MB)." % (csv_file.size/(1000*1000),))
            return HttpResponseRedirect(reverse("certifiedapp:upload_csv"))

        file_data = csv_file.read().decode("utf-8")

        x=[]
        y=[]
        fig=Figure()
        ax=fig.add_subplot(111)
        import csv
        import io
        io_string = io.StringIO(file_data)
        plots = csv.reader(io_string, delimiter=',')
        for row in plots:
            x.append(int(row[0]))
            y.append(int(row[1]))
        ax.plot(x, y, label='$x^3$')
        ax.set_xlabel('X axis')
        ax.set_ylabel('Y axis')
        ax.set_title('Sample Data Graph')
        canvas = FigureCanvas(fig)
        response = HttpResponse( content_type = 'image/png')
        canvas.print_png(response)
        return response

@login_required
def test_list(request):
    t_list = Testlist.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(t_list, 5)
    try:
        t_list = paginator.page(page)
    except PageNotAnInteger:
        t_list = paginator.page(1)
    except EmptyPage:
        t_list = paginator.page(paginator.num_pages)
    context = { 't_list' : t_list,'t_list':t_list}
    return render(request,'certifiedapp/Test_List.html',context)

@login_required
def takepredict(request):
    import numpy as np
    A = np.array([[1, 2, 3], [4, 5, 6]]) #iprint A # [[1 2 3] # [4 5 6]]
    context = {'example1':A}
    return render(request,'certifiedapp/Take_Test.html', context)

def test_results(request):

    return render(request,'certifiedapp/Test_Results.html')


# student free test.
@login_required
def student_freetest(request):
    stu_user = User.objects.get(username=request.user)
    paper = Paperstype.objects.get(pk=2)
    request.session['papertype'] = paper.id
    print(request.session['papertype'])

    questions = Questions.objects.filter(papertype=paper)
    que_count = questions.count()
    request.session['total_que'] = que_count
    context = {'stu_questions':questions, 'que_count':que_count}



    print(stu_user)
    return render(request, 'certifiedapp/free_test.html', context)
    # return HttpResponse(questions)



@login_required
def student_test_submit(request):
    try:
        print(request.session['papertype'])
    except:
        raise ValueError('Your test done....')
    print(request.session['total_que'])
    total_que = int(request.session['total_que'])
    paper_type = Paperstype.objects.get(pk=int(request.session['papertype']))
    print('Total marks-->:',request.POST.get('totalmarks'))
    total_marks = int(request.POST.get('totalmarks'))

    stu_results = StudentResults(stu_user=request.user, total_marks = total_marks, total_question = total_que,paper_type = paper_type)
    stu_results.save()
    del request.session['papertype']
    request.session['student_resultid'] = stu_results.id
    # print(request.POST)
    return redirect('certifiedapp:student_testresult')
    # return HttpResponse(stu_results)

@login_required
def student_testresult(request):
    student_resultid = int(request.session['student_resultid'])

    return render(request, 'certifiedapp/student_results.html', context={'sturesults':StudentResults.objects.get(pk=student_resultid)})


def forgot_password(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        import random

        otp = "{}".format(random.randint(1000,9000))
        try:
            user = User.objects.get(username=name)
            if user:
                send_mail('Password reset verification code ', otp,
                [user.email], False)
            return render(request, 'forgot_password_success.html', {'otp':otp,'user_id':user.id})
        except Exception as e:

            user = User.objects.get(username=name)
            if user:
                send_mail('Password reset verification code ', otp,
                [user.email], False)
            return render(request, 'forgot_password_success.html', {'otp':otp,'user_id':user.id})


            return render(request, 'forgot_password.html', {'error':e})

    return render(request, 'forgot_password.html', {})


def forget_password_reset(request):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        password = request.POST.get('pass')
        users=User.objects.get(id=user_id)
        users.set_password(password)
        users.save()
        return render(request, 'forget_password_done.html', {})

templates/certifiedapp/Take_Test.html
{% block content %}
{%include 'header.html'%}


<h3>Hi, <b>{{ request.user }}</b>. Welcome to Take Test.</h3>
   

<!-- Page Content -->



{% for message in messages %}
    <div class="alert alert-success">
        <a class="close" href="#" data-dismiss="alert">×</a>
        {{ message }}
    </div>
{% endfor %}
<form action="{% url 'certifiedapp:upload_csv' %}" method="POST" enctype="multipart/form-data" class="form-horizontal"> 
{% csrf_token %}
<div class="form-group">
    <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label">File: </label>
    <div class="col-md-8">
        <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
    </div>                    
</div>
<div class="form-group">                    
    <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
         <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
    </div> 
</div>
</form>






	

{%include 'footer.html'%}
{%include 'script_style.html'%}


{% endblock %}

templates/certifiedapp/Test_List.html
{% extends 'base.html' %}


{% block content %}
{% include 'submenu.html'%}


<div class="container">

<h3>Hi, <b>{{ request.user }}</b>. Welcome to Test List.</h3>
    </div>
{%include 'leftmenu.html'%}


<!-- Page Content -->
<div style="margin-left:25%">

<div class="w3-container w3-teal">
  <h1>Certified Test List</h1>
</div>

<script>
$(function() {
//----- OPEN
$('[data-popup-open]').on('click', function(e)  {
var targeted_popup_class = jQuery(this).attr('data-popup-open');
$('[data-popup="' + targeted_popup_class + '"]').fadeIn(350);
e.preventDefault();
});
//----- CLOSE
$('[data-popup-close]').on('click', function(e)  {
var targeted_popup_class = jQuery(this).attr('data-popup-close');
$('[data-popup="' + targeted_popup_class + '"]').fadeOut(350);
e.preventDefault();
});
});
</script>
<style>
/* Outer */
.popup {
width:100%;
height:100%;
display:none;
position:fixed;
top:0px;
left:0px;
background:rgba(0,0,0,0.75);
}
/* Inner */
.popup-inner {
max-width:700px;
width:90%;
padding:40px;
position:absolute;
top:50%;
left:50%;
-webkit-transform:translate(-50%, -50%);
transform:translate(-50%, -50%);
box-shadow:0px 2px 6px rgba(0,0,0,1);
border-radius:3px;
background:#fff;
}
/* Close Button */
.popup-close {
width:30px;
height:30px;
padding-top:4px;
display:inline-block;
position:absolute;
top:0px;
right:0px;
transition:ease 0.25s all;
-webkit-transform:translate(50%, -50%);
transform:translate(50%, -50%);
border-radius:1000px;
background:rgba(0,0,0,0.8);
font-family:Arial, Sans-Serif;
font-size:20px;
text-align:center;
line-height:100%;
color:#fff;
}
.popup-close:hover {
-webkit-transform:translate(50%, -50%) rotate(180deg);
transform:translate(50%, -50%) rotate(180deg);
background:rgba(0,0,0,1);
text-decoration:none;
}
</style>
<div class="popup" data-popup="popup-1">
<div class="popup-inner">
<h2>Python Certification</h2>
<p> ...... Coming soon</p>
<p><a data-popup-close="popup-1" href="#">Close</a></p>
<a class="popup-close" data-popup-close="popup-1" href="#">x</a>
</div>
</div>
<div class="w3-container">
<br>

<table border=2 width=50%>
<tr>
<th>Id</th>
<th> Test Name </th>
 
</tr>
<tr>
<td>0</td>
<td> <a data-popup-open="popup-1" href="#"  class="btn">Python</a> </td>
</tr>

{%for i in t_list%}
<tr>
<td>{{i.id}}</td>
<td> <a href="" class="w3-bar-item w3-button"> {{i.tst_name}} </a> </td>
</tr>
{%endfor%}
</table>


{% if t_list.has_other_pages %}
  <div class="pagination">
    {% if t_list.has_previous %}
      <a href="?page={{ t_list.previous_page_number }}">&laquo;</a>
    {% else %}
      <span class="disabled">&laquo;</span>
    {% endif %}


    {% for i in t_list.paginator.page_range %}
      {% if t_list.number == i %}
        <span class="active">{{ i }} <span class="sr-only">(current)</span></span>
      {% else %}
        <a href="?page={{ i }}">{{ i }}</a>
      {% endif %}
    {% endfor %}
    {% if t_list.has_next %}
      <span><a href="?page={{ t_list.next_page_number }}">&raquo;</a></span>
    {% else %}
      <span class="disabled">&raquo;</span>
    {% endif %}
  </div>
{% endif %}

</div>

</div>





{% endblock %}

templates/certifiedapp/admindashbord.html
{% extends 'base.html' %}


{% block content %}
<div class="container">

<h3>Username: <b>{{ request.user }}</b></h3>
    <p>
        Admin dashbord
    </p>
    <ul>
        <li>
            <div class="well">
                <a href="{% url 'subjectapp:subjectlist' %}">View all subjects </a>
            </div>
        </li>
        <li>
            <div class="well">
                <a href="{% url 'subjectapp:paperslist' %}">View all paper types </a>
            </div>
        </li>
        <li>
            <div class="well">
                <a href="{% url 'subjectapp:questionlist' %}">View all Questions & Answers</div>
        </li>
        <li>
            <div class="well">

                <a href ="{% url 'subjectapp:results' %}">View Results</a>


            </div>
        </li>

    </ul>
</div>

{% endblock %}

templates/certifiedapp/free_test.html
{% block content %}
{%include 'header.html'%}
   <h2>Hi, Welcome {{request.user}}</h2>


<div class="container">

    <form action="{% url 'certifiedapp:student_test_submit' %}" method="POST" >

  <h2>Student Free TEST</h2>
     <input type="text" value="0" id="finalmarks" name="totalmarks" hidden>
     <button class="btn btn-danger" type="submit" onclick="submitTest()" value="Submit Test" style="font-weight: bolder">Submit Test</button>
  <div class="panel panel-default">
    <div class="panel-body">
        <div class="table">
            <table class="table">
                {% csrf_token %}
                {% for que in stu_questions %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>
                       <b>QUESTION:-</b> {{ que.question_name }} <br>
                        <div class="well well-sm"><input type="radio"  value="1" name="option{{forloop.counter}}" id="{{forloop.counter}}A">{{ que.option1 }}</div>
                        <div class="well well-sm"><input type="radio" value='2' name="option{{forloop.counter}}" id="{{forloop.counter}}B">{{ que.option2 }}</div>
                        <div class="well well-sm"><input type="radio" value="3" name="option{{forloop.counter}}" id="{{forloop.counter}}C">{{ que.option3 }}</div>
                        <div class="well well-sm"><input type="radio" value="4" name="option{{forloop.counter}}" id="{{forloop.counter}}D">{{ que.option4 }}</div>
                        <div class="well">
                             <input type="radio" value="{{ que.answer }}" id="{{forloop.counter}}ANSWER" hidden>
                        </div>
                    </td>

                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
  </div>
    </form>
</div>


<script>

                function submitTest() {
                alert('submit test');
                var marks = 0;
                var x = 3;
                for (var i = 1; i < x + 1; i++) {
                    if (document.getElementById(i + "A").checked) {
                        if (document.getElementById(i + "A").value == document.getElementById(i + "ANSWER").value)
                            marks++;
                    }
                    else if (document.getElementById(i + "B").checked) {
                        if (document.getElementById(i + "B").value == document.getElementById(i + "ANSWER").value)
                            marks++;
                    }
                    else if (document.getElementById(i + "C").checked) {
                        if (document.getElementById(i + "C").value == document.getElementById(i + "ANSWER").value)
                            marks++;
                    }
                    else if (document.getElementById(i + "D").checked) {
                        if (document.getElementById(i + "D").value == document.getElementById(i + "ANSWER").value)
                            marks++;
                    }
                    else { }
                }
                // alert("Your Score - " + marks);
                document.getElementById('finalmarks').value = marks;
                alert("Your Score is - " + marks);
                $("#formid").submit();
            }
        // Marks calculations Ends

</script>

{%include 'footer.html'%}
{%include 'script_style.html'%}
{% endblock %}

templates/certifiedapp/student_results.html
{% block content %}
{%include 'header.html'%}
   <h2>Hi, Welcome {{request.user}}</h2>

<div class="container">
    <div class="well">
        YOUR SCORE : {{ sturesults.total_marks }} / {{ sturesults.total_question }}
    </div>
</div>


{%include 'footer.html'%}
{%include 'script_style.html'%}
{% endblock %}

templates/certifiedapp/userdashbord.html
{% block content %}
{%include 'header.html'%}
{% load static %}
<!-- the code add for slider-->
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<style>
    .card-banner {
    display: flex;
    position: relative;
    overflow: hidden;
    background-color: #fff;
    background-size: cover;
    border-radius: 5px;
}
.card-banner .card-body {
    background-size: cover;
    position: relative;
    z-index: 10;
}


/* overlay effects */
.overlay-cover {
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    position: absolute;
    width: 100%;
}
.overlay {
    background-color: rgba(0,0,0,0.65);
    z-index: 10;
    padding: 1.25rem;
    color: #fff;
}
.overlay-grad {
    position: relative;
}

.overlay-grad::before {
    position: absolute;
    content: "";
    display: block;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: #e83e8c;
    background: -webkit-gradient(linear, left top, right bottom, from(#007bff), to(#e83e8c));
    background: linear-gradient(to bottom right, #007bff, #e83e8c);
    opacity: .6;
    transition: .5s;
}
.overlay-grad:hover:before{
     opacity: .9;
}
</style>
<!-- the code end of rslider-->

<div class="container">
   <h3 align="left"> Hi, {{ request.user }}
</h3><br><br><br><hr>
    <div class="row">
	    	<aside class="col-sm-4">
               <!-- <p>Card banner overlay </p>
-->
<div class="card-banner  overlay-grad" style="height:250px; background-image: url('https://codyparker.com/wp-content/uploads/2016/10/dj-react.png');">
  <div class="card-body text-white">
   <!-- <h5 class="card-title">Primary text as title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  --></div>
</div> <!-- card.// -->

            </aside>
            <aside class="col-sm-4">
         <!--<p>Card banner overlay dark </p>
--><div class="card-banner" style="height:250px; background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRh_imCdazkJyK6ZF_OaYu7IULJw-B7vasx4T6gpV4xdw0h1hMU');">
  <article class="overlay overlay-cover d-flex align-items-center justify-content-center">
    <div class="text-center">

    	<a href="#" class="btn btn-warning btn-sm"> View more </a>
   </div>
  </article>
</div> <!-- card.// -->

            </aside>
            <aside class="col-sm-4">

<div class="card-banner align-items-end" style="height:250px; background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdbmAtYs-2iBZBmaqfveF5s2vlPdCussqyqvgs4O6ozIjq-uOw');">
	<article class="overlay m-4 w-100">

    	<a href="#" class="btn btn-warning btn-sm"> View more </a>
    </article>
</div> <!-- card.// -->

            </aside>
	</div>
</div>


<br><br>





{%include 'footer.html'%}
{%include 'script_style.html'%}
{% endblock %}