bugtrackapp/urls.py
from django.conf.urls import url

from bugtrackapp import views


urlpatterns =[
    url(r'^blog_id/(\d+)/', views.blog_id, name="blogid"),
    url(r'^rscbugtrack/$', views.rscbugtrack, name="rscbugtrack"),
    url(r'^feedback/$', views.comments, name="comments"),
    url(r'^aboutus/$', views.aboutus, name="aboutus"),
    url(r'^ourteam/$', views.ourteam, name="ourteam"),
    url(r'^contactus/$', views.contactus, name="contactus"),

    url(r'^home/$', views.rschome, name="rschome"),

 ]

certifiedapp/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from certifiedapp import views as core_views

urlpatterns =[
    # url(r'^login/$', auth_views.login,  name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login/'}, name="logout"),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^change_password/$', core_views.change_password, name="change_password"),
    url(r'^userdashbord/$', core_views.userdashbord, name='userdashbord'),
    url(r'^Test_List/$',core_views.test_list,name='Testlist'),
    url(r'^Take_Predict/$',core_views.takepredict,name='Takepredict'),
    url(r'^charts/simple.png$', core_views.simple),
    url(r'^forgot_password/$', core_views.forgot_password, name="forgot_password"),
    url(r'^upload/csv/$', core_views.upload_csv, name='upload_csv'),
    url(r'^student_freetest/$', core_views.student_freetest, name='student_freetest'),
    url(r'^student_test_submit/$', core_views.student_test_submit, name='student_test_submit'),
    url(r'^student_testresult/$', core_views.student_testresult, name='student_testresult'),
    url(r'forget_password_reset/',core_views.forget_password_reset , name='forget_password_reset'),
]

hc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
# from hc.accounts.views import login as hc_login
# import bugtrackapp
from bugtrackapp.views import rschome as home

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # url(r'^admin/login/', hc_login, {"show_password": True}),
    url(r'^admin/', admin.site.urls),
    url(r'^$',home),
    url(r'login/$', auth_views.login, {'template_name': 'registration/cert_app_login.html'} ,name='login'),

    url(r'^', include('bugtrackapp.urls', namespace="bugtrackapp")),
    url(r'^', include('certifiedapp.urls',namespace="certifiedapp")),
    url(r'^', include('subjectsapp.urls',namespace="subjectapp")),
    url(r'^', include('toolsapp.urls',namespace="toolsapp")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toolsapp/urls.py
from django.conf.urls import url , include
from toolsapp import views

urlpatterns =[
    url(r'^toolshome/$', views.toolshome,  name='toolshome'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Author(models.Model):
    name = models.CharField(max_length=64)
    email = models.CharField(max_length=64)

    def __str__(self):
        return "%s (%s)" % (self.name, self.email)

category_choices = (('PY','Python'),('ML','Machine Learning'),('MLWPY','Machine Learning with Python'),('FAQ','FAQ'),)

class Post(models.Model):
    title = models.CharField(max_length=64)
    date = models.DateTimeField()
    author = models.ForeignKey(Author)
    body = models.TextField()
    description = models.CharField(max_length=50, default="None")
    summary = models.CharField(max_length=300 , default="None")
    post_image = models.ImageField(upload_to='blogimg/', default="Null")
    document = models.FileField(upload_to='blogimg/', default="Null")
    category = models.CharField(max_length=255,default='ML',choices=category_choices)

    def __str__(self):
        return "%s (%s)" % (self.title, self.author.name)


class PostComment(models.Model):
    comment = models.TextField()
    post_id =models.ForeignKey(Post)
    user_name =  models.ForeignKey(User)
    date = models.DateTimeField()

blog/views.py
from django.shortcuts import render

# Create your views here.

templates/bad_link.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="hc-dialog">
            <h1>Incorrect Link</h1>
            <div class="dialog-body">
                <p>
                    The link you just used is incorrect.
                    If you copy-pasted the link, please make sure you did not
                    miss any characters.
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load compress staticfiles %}

    <meta charset="utf-8">
    <title>RedSunCube</title>
    <link rel="shortcut icon" href="{%  static 'img/favicon.ico' %}">
    <meta name="description" content="RSC projects.1">
    <meta name="keywords" content="RSC projects.">
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% compress css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nouislider.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nouislider.pips.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/selectize.bootstrap3.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/snippet-copy.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/docs.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/docs_cron.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/welcome.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/my_checks.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/my_checks_mobile.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/my_checks_desktop.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/pricing.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/syntax.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/channels.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/channel_checks.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/log.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/add_pushover.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/settings.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/last_ping.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/checkbox.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/radio.css' %}" type="text/css"> {% endcompress %}

    <style type="text/css">
       
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.Popup').click(function() {
                var newwindow = window.open($(this).prop('href'), '', 'height=800,width=800');
                if (window.focus) {
                    newwindow.focus();
                }
                return false;
            });

            $('#NewTab').click(function() {
                $(this).target = "_blank";
                window.open($(this).prop('href'));
                return false;
            });
        });
    </script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/base_footer.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/base_need1.css' %}" type="text/css">
    <style type="text/css">
      
    </style>
</head>

<body class="page-{{ page }}">
    <nav id="myNavbar" class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="#"><img id="logo" height="50" width="200" src="{% static 'img/logo_ch.png'%}">
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <a class="navbar-brand" href="/home" title="">Home</a>
                <a class="navbar-brand" href="{% url 'bugtrackapp:aboutus' %}" title="">About Us</a>
                <!-- <a class="Popup navbar-brand" href="{% url 'bugtrackapp:rscbugtrack' %}" title="">BugTrack || </a>-->
                <!--<a class="navbar-brand" href="{% url 'toolsapp:toolshome' %}" title="">Docs</a>-->{% if user.is_superuser %}
                <a class="navbar-brand" href="https://github.com/rscbugtrack/rscpro.git" title="RSCGithub">Github </a>{% endif %}
                <a class="navbar-brand" href="{% url 'bugtrackapp:ourteam' %}" title="">Our Team</a>
                <a class="navbar-brand" href="{% url 'bugtrackapp:contactus' %}" title="">Contact Us</a>

            </div>

        </div>

    </nav>
    <div class="container">

        {% if user.is_superuser %}
            <a href="{% url 'certifiedapp:userdashbord' %}"><span class="glyphicon glyphicon-home"></span>AdminHome</a></div>
        {% endif %}

    </div>

    {% block containers %}
        <div class="container">
            {% block content %} 
            
            {% endblock %}
        </div>

    {% endblock %}
   
    <!--header-->

    <div class="footer-bottom">

        <div class="container">

            <div class="row">

                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

                    <div class="copyright">

                        © 2018, REDSUNCUBE, All rights reserved

                    </div>

                </div>

                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

                    <div class="design">

                        <a href="#">Franchisee </a> | <a target="_blank" href="http://www.redsuncube.com">Web Design & Development by Redsuncube India</a>

                    </div>

                </div>

            </div>

        </div>

    </div>
    <!-- footer end -->

</body>

</html>

templates/base_bare.html
{% load hc_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% site_name %} - Monitor Cron Jobs. Get Notified When Your Cron Jobs Fail{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>
    {% load compress staticfiles %}
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

    {% compress css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">

    {% endcompress %}
</head>
<body class="page-{{ page }}">
    {% block containers %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    {% endblock %}
</body>
</html>

templates/contact_us.html
{% block content %}
{%include 'home_header.html'%}
{% load static %}

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>

<div class="container">
	<div class="row-fluid"><h1>Contact Us</h1>
        <div class="span8">

<iframe  width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15230.812664402658!2d78.4945914!3d17.3780107!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xa9c51b89db51e1cd!2sRedSunCube!5e0!3m2!1sen!2sin!4v1518075758450" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>


      	<div class="span4">
    		<h2>India</h2>
    		<address>
    			<strong>Redsuncube India</strong><br>
    			16-7-808/3, Vinayak Street<br>
    			Malakpet<br>
    			Hyderabad-500024<br>

    			<abbr title="Phone">P:</abbr>9908531889
    		</address>
    	</div>
    </div>
</div>

{%include 'script_style.html'%}
{%include 'footer_home.html'%}
{% endblock %}

templates/feedback.html
{%extends "base.html"%}
{%block content%}
{% load compress staticfiles %}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="{% static 'css/home_need1.css' %}" type="text/css">

<div class="container-fluid">
    <div class="row content">
        <div class="col-sm-9">
            {%for i in blog_page%}
            <hr>
            <h3>{{i.title}}</h3>
            <h5><span class="glyphicon glyphicon-time"></span> {{i.date}}.</h5>
            <h5><span class="label label-success">RSC</span></h5>
            <br>
            <p>{{i.summary}}</p><a href="/blog_id/{{i.id}}/">Read More</a>
            <hr> {%endfor%} {% if blog_page.has_other_pages %}
            <ul class="pagination">
                {% if blog_page.has_previous %}
                <li><a href="?page={{ blog_page.previous_page_number }}">&laquo;</a></li>
                {% else %}
                <li class="disabled"><span>&laquo;</span></li>
                {% endif %} {% for i in blog_page.paginator.page_range %} {% if blog_page.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span>
                </li>
                {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %} {% endfor %} {% if blog_page.has_next %}
                <li><a href="?page={{ blog_page.next_page_number }}">&raquo;</a></li>
                {% else %}
                <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
            {% endif %}


            <!-- feedback-->
            <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->


<div class="container">
    <div class="row">
        <div class="panel panel-default widget">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-comment"></span>
                <h3 class="panel-title">
                    Recent Comments</h3>

            </div>
            <div class="panel-body">
                <ul class="list-group">
                    {% for i in comments%}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-xs-10 col-md-11">
                                <div>
                                    <a href="http://www.jquery2dotnet.com/2013/10/google-style-login-page-desing-usign.html">
                                        {{i.comment}}</a>
                                    <div class="mic-info">
                                        By: <a href="#">{{i.customer_name}}</a> on {{i.date}}
                                    </div>
                                </div>

                            </div>
                        </div>
                    </li>
                    {% endfor %}

                </ul>
                <h3>Comments/Feedback</h3>
               <form action="" method="post">
    {% csrf_token %}

   {{form.as_p}}<br>
   <input type="submit" value="Submit" />
</form>
            </div>
        </div>
    </div>
</div>
<style>
.widget .panel-body { padding:0px; }
.widget .list-group { margin-bottom: 0; }
.widget .panel-title { display:inline }
.widget .label-info { float: right; }
.widget li.list-group-item {border-radius: 0;border: 0;border-top: 1px solid #ddd;}
.widget li.list-group-item:hover { background-color: rgba(86,61,124,.1); }
.widget .mic-info { color: #666666;font-size: 11px; }
.widget .action { margin-top:5px; }
.widget .comment-text { font-size: 12px; }
.widget .btn-block { border-top-left-radius:0px;border-top-right-radius:0px; }
</style>
            <!-- end of feedback -->





                {{i}}<br>

        </div>

        <div class="col-sm-3 sidenav">
            <i>To do certification practice click on login</i>
            <br>
            <a href="/login">
                <button>Login<span class="glyphicon glyphicon-log-in"></span></button>
            </a>
            <hr>
            <h4><font color=grey><u><i>Latest Post</i></u></font></h4>
            <ul class="nav nav-pills nav-stacked">
                {%for i in blog_obj%}
                <li><a href="/blog_id/{{i.id}}/">{{i.title}}</a></li>
                {%endfor%}
            </ul>
            <br>
            <hr>
            <a href="http://www.reliablecounter.com" target="_blank">
                <img src="http://www.reliablecounter.com/count.php?page=redsuncube.com10930430&digit=style/plain/1/&reloads=0" alt="" title="" border="0"></a>
            <br />
            <a href="https://info.flagcounter.com/w6S1">
                <img src="https://s11.flagcounter.com/count2/w6S1/bg_FFFFFF/txt_000000/border_CCCCCC/columns_2/maxflags_10/viewers_0/labels_0/pageviews_0/flags_0/percent_0/" alt="Flag Counter" border="0">
            </a>
        </div>
    </div>

</div>
{%endblock%}

templates/footer.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">


<footer>
         <p style="color:#0a93a6;text-decoration:none;">© 2018<a href="#"> redsuncube india </a>, All rights reserved 2018-2019.<br>
    <img src="https://www.reliablecounter.com/count.php?page=redsuncube.com8839706&digit=style/plain/33/&reloads=1" alt="" title="" border="0">

         </p>



   </footer>
    <style>
        /* Footer */

footer{
   background-color: #102c58;
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    height: 80px;
    text-align: center;
    color: #CCC;
}

footer p {
    padding: 10.5px;
    margin: 0px;
    line-height: 100%;
}
    </style>

templates/footer_home.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<footer>
         <p style="color:#0a93a6;text-decoration:none;">© 2018<a href="#"> redsuncube india </a>, All rights reserved 2018-2019.<br>
    <img src="https://www.reliablecounter.com/count.php?page=redsuncube.com8839706&digit=style/plain/33/&reloads=1" alt="" title="" border="0">

         </p>


   </footer>

           <p align="right">     <img src="https://s11.flagcounter.com/count2/w6S1/bg_FFFFFF/txt_000000/border_CCCCCC/columns_2/maxflags_10/viewers_0/labels_0/pageviews_0/flags_0/percent_0/" alt="Flag Counter" border="0">
</p>

    <style>
        /* Footer */

footer{
   background-color: #102c58;
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    height: 80px;
    text-align: center;
    color: #CCC;
}

footer p {
    padding: 10.5px;
    margin: 0px;
    line-height: 100%;
}
    </style>

templates/forget_password_done.html
{% extends 'base.html' %}
{% block content %}




<div class="container-fluid column-starter">
	<!------------ Panel Class ------------->
    <div class="margin-t-20"></div>
	<div class="row">
	    <div class="col-md-3 sidebar">
	        <div class="panel">
    	       <div class="panel-body ">
                <div class="sidebar-nav">
                 <div class="sidebar panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                          <a data-toggle="collapse" href="/login" class="" aria-expanded="true">Login <i class="fa fa-angle-down pull-right"></i></a>
                        </h4>
                      </div>

                 </div>
                 <div class="sidebar panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                          <a href="/signup" data-toggle="collapse" href="#sidemenu2"  class="" aria-expanded="true">Signup <i class="fa fa-angle-down pull-right"></i></a>
                        </h4>
                      </div>

                 </div>

                </div>


    	        </div>

	        </div>
	    </div>
	    <div class="col-md-9">
	        <div class="panel">
	       <div class="panel-body">



<h1>change password is done</h1>
please click login to for login


	        </div>

	        </div>

	    </div>

	</div>
</div>





{% endblock %}

templates/header.html
<html lang="en" >

<head>
    <meta charset="UTF-8">
    <title>Redsuncube:Home</title>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css'><link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css'><link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css'>
    <style class="cp-pen-styles">@import url("https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700&subset=latin-ext");
</style></head>


<body class="sidebar-is-reduced">
  <header class="l-header">
    <div class="l-header__inner clearfix">
      <div class="c-header-icon js-hamburger">
        <div class="hamburger-toggle"><span class="bar-top"></span><span class="bar-mid"></span><span class="bar-bot"></span></div>
      </div>
      <div class="c-header-icon has-dropdown"><span class="c-badge c-badge--header-icon animated shake">12</span><i class="fa fa-bell"></i>
        <div class="c-dropdown c-dropdown--notifications">
          <div class="c-dropdown__header"></div>
          <div class="c-dropdown__content"></div>
        </div>
      </div>
      <div class="c-search">
        <input class="c-search__input u-input" placeholder="Search..." type="text"/><button type="button" class="btn btn-default btn-sm">
          <span class="glyphicon glyphicon-search"></span> Search
        </button>
      </div>
      <div class="header-icons-group">

        <div class="c-header-icon reset"> <a title="change password" href="/change_password"><i class="fa fa-lock"></i></a></div>
        <div class="c-header-icon logout"><a title="SignOut" href="/logout"><i class="fa fa-power-off"></i></a></div>
      </div>
    </div>
  </header>
  <div class="l-sidebar">
    <div class="logo">
      <div class="logo__txt" title="Redsuncube"><a href="/userdashbord/">RSC</a></div>
    </div>
    <div class="l-sidebar__content">
      <nav class="c-menu js-menu">
        <ul class="u-list">
          <li class="c-menu__item is-active" data-toggle="tooltip" title="Predict Dataset">
          <div class="c-menu__item__inner"><i class="fa fa-file-text-PD"><a href="/Take_Predict">PD</a></i>
          <div class="c-menu-item__title"><span><a href='/Take_Predict'>Predict Dataset</span></div>
          </div>
          </li>



        </ul>


		      </nav>
    </div>
  </div>
</body>
<main class="l-main">
  <div class="content-wrapper content-wrapper--with-bg">

templates/rschome.html
{% extends "base.html" %}

{% block containers %}
<div class="index-bleed">
<div class="container">
    <div class="row">
    <div class="col-sm-12">
    {% load staticfiles compress %}
    <!--<img src="{% static 'img/open-source-banner.jpg' %}">-->
    </div>
    </div>
</div>

{% endblock %}

templates/submenu.html
{% if request.user %}
<div align="right">
Time left = <span id="timer"></span>
</div>
{%endif%}

<script>
document.getElementById('timer').innerHTML =
  05 + ":" + 00;
startTimer();

function startTimer() {
  var presentTime = document.getElementById('timer').innerHTML;
  var timeArray = presentTime.split(/[:]+/);
  var m = timeArray[0];
  var s = checkSecond((timeArray[1] - 1));
  if(s==59){m=m-1}
  //if(m<0){alert('timer completed')}

  document.getElementById('timer').innerHTML =
    m + ":" + s;
  setTimeout(startTimer, 1000);
}

function checkSecond(sec) {
  if (sec < 10 && sec >= 0) {sec = "0" + sec}; // add zero in front of numbers < 10
  if (sec < 0) {sec = "59"};
  return sec;
}
</script>

<div align="right">
 <a href="/userdashbord"><span class="glyphicon glyphicon-home"></span>Home</a>

||
<font color=red><span class="glyphicon glyphicon-user"></span><font color= blue>{{ request.user }} </font></font>||
<a href="/change_password"><button>Change_Password</button></a>

<a href="/logout"><button>Logout</button></a>
</div>

<hr>