hc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
# from hc.accounts.views import login as hc_login
# import bugtrackapp
from bugtrackapp.views import rschome as home

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # url(r'^admin/login/', hc_login, {"show_password": True}),
    url(r'^admin/', admin.site.urls),
    url(r'^$',home),
    url(r'login/$', auth_views.login, {'template_name': 'registration/cert_app_login.html'} ,name='login'),

    url(r'^', include('bugtrackapp.urls', namespace="bugtrackapp")),
    url(r'^', include('certifiedapp.urls',namespace="certifiedapp")),
    url(r'^', include('subjectsapp.urls',namespace="subjectapp")),
    url(r'^', include('toolsapp.urls',namespace="toolsapp")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subjectsapp/urls.py
from django.conf.urls import include, url

from subjectsapp import views


urlpatterns =[
    url(r'^allsubjects/$', views.subjectlist, name="subjectlist"),
    url(r'^addsubject/$', views.add_subject, name="add_subject"),
    url(r'^editsubject/(?P<pk>\d+)$', views.edit_subject, name="editsubject"),
    url(r'^allpapers/$', views.paperslist, name="paperslist"),
    url(r'^addpapers/$', views.add_papers, name="add_papers"),
    url(r'^editpapertype/(?P<pk>\d+)$', views.edit_papertype, name="edit_papertype"),
    url(r'^allquestions/$', views.questionlist, name="questionlist"),
    url(r'^addquestions/$', views.add_questions, name="add_questions"),
    url(r'^editquestiontype/(?P<pk>\d+)$', views.edit_questions, name="edit_questions"),
    url(r'^results/$', views.results, name="results"),


]

subjectsapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
# Create your models here.

# displays all subjects
class TechType(models.Model):
    subject_name = models.CharField(max_length=30, help_text='Add the technology type ..like python , jave and mysql etc..')
    status = models.BooleanField(default=False)
    user = models.ForeignKey(User, null=True)

    def __str__(self):
        return '{0}'.format(self.subject_name)

    def get_absolute_url(self):
        return reverse('subjectapp:editsubject', kwargs={'pk': self.pk})


# displays all papers type

mode_choices = (('B','Beginner'),('I','Intermediate'),('A','Advanced'),)
class Paperstype(models.Model):
    subject_name = models.ForeignKey(TechType)
    mode = models.CharField(max_length=2,choices=mode_choices, help_text='Mode of exam')
    papernumber = models.PositiveSmallIntegerField(help_text='Number of paper for exam')
    status = models.BooleanField(help_text='Activation status')

    def __str__(self):
        return '{0}-{1}-{2}'.format(self.subject_name,self.mode,self.papernumber)
    @property
    def displaymode(self):
        return '{0}'.format(self.mode)

    def get_absolute_url(self):
        return reverse('subjectapp:edit_papertype', kwargs={'pk': self.pk})


from datetime import datetime

class Questions(models.Model):
    papertype = models.ForeignKey(Paperstype,null=True)
    question_name = models.CharField(max_length=500, help_text='Full Question name')
    option1 = models.CharField(max_length=50, help_text='A')
    option2 = models.CharField(max_length=50, help_text='B')
    option3 = models.CharField(max_length=50, help_text='C')
    option4 = models.CharField(max_length=50, help_text='D')
    answer = models.CharField(max_length=50, help_text='Answer')
    status = models.BooleanField(default=True)
    date_added = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return 'Question: {0}'.format(self.question_name)

    def get_absolute_url(self):
        return reverse('subjectapp:edit_questions', kwargs={'pk': self.pk})


# todo test time in papers type
# todo student answer model create
# answer value == choice field ..

subjectsapp/forms.py
from .models import Paperstype,Questions
from django import forms


# all forms..
class PaperstypeForm(forms.ModelForm):
    class Meta:
        model = Paperstype
        fields = ['subject_name','mode','papernumber','status']


class QuestionsForm(forms.ModelForm):
    question_name = forms.Textarea()

    class Meta:
        model = Questions
        exclude = ('date_added',)

subjectsapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django import forms
from django.contrib.auth.decorators import login_required
from subjectsapp.forms import PaperstypeForm,QuestionsForm
# Create your views here.

from subjectsapp.models import TechType,Paperstype,Questions#,StudentResults


class Subjectform(forms.ModelForm):
    class Meta:
        model = TechType
        fields = ['subject_name','status']


@login_required
def subjectlist(request):
    subjects_list = TechType.objects.all()
    context ={'subjects':subjects_list}
    template = 'subjectsapp/subject_list.html'
    return render(request,template,context)





def add_subject(request):
    subform = Subjectform(request.POST)

    if subform.is_valid():
        subject_name =request.POST.get('subject_name')
        status = request.POST.get('status')
        if status:
            status=True
        else:
            status=False
        user =request.user
        t = TechType(subject_name=subject_name,status=status,user=user)

        t.save()
        return redirect('subjectapp:subjectlist')

    subform = Subjectform()

    template = 'subjectsapp/subjectadd_list.html'
    context = {'subform':subform}
    return render(request,template,context)


@login_required
def edit_subject(request, pk):

    subject = TechType.objects.get(pk=pk)
    template = 'subjectsapp/subjectedit.html'
    form = Subjectform(request.POST or None, instance=subject)
    context= { 'form':form }
    if request.method == 'POST':
        form.save()
        return redirect('subjectapp:subjectlist')
    return render(request,template,context)


# papertype CRUD

@login_required
def paperslist(request):
    allpapers = Paperstype.objects.all()
    context = {'paperslist':allpapers}
    template = 'subjectsapp/papers_list.html'
    return render(request, template,context)


@login_required
def add_papers(request):
    paperform = PaperstypeForm(request.POST)

    if paperform.is_valid():
        paperform.save()

        return redirect('subjectapp:paperslist')

    paperform = PaperstypeForm()

    template = 'subjectsapp/papersadd_list.html'
    context = {'paperform':paperform}
    return render(request,template,context)

@login_required
def edit_papertype(request, pk):
    paper = Paperstype.objects.get(pk=pk)
    template = 'subjectsapp/papersedit.html'
    form = PaperstypeForm(request.POST or None, instance=paper)
    context = {'form':form}
    if request.method == 'POST':
        form.save()
        return redirect('subjectapp:paperslist')
    return render(request,template,context)


# questions CRUD
@login_required
def questionlist(request):
    allquestions = Questions.objects.all()
    context = {'questions':allquestions}
    template = 'subjectsapp/questions_list.html'
    return render(request, template,context)


@login_required
def add_questions(request):
    question_form = QuestionsForm(request.POST)

    if question_form.is_valid():
        question_form.save()

        return redirect('subjectapp:questionlist')

    question_form = QuestionsForm()

    template = 'subjectsapp/questionadd_list.html'
    context = {'question_form':question_form}
    return render(request,template,context)



@login_required
def edit_questions(request, pk):
    que = Questions.objects.get(pk=pk)
    template = 'subjectsapp/questionedit.html'
    form = QuestionsForm(request.POST or None, instance=que)
    context = {'form':form}
    if request.method == 'POST':
        form.save()
        return redirect('subjectapp:questionlist')

    return render(request,template,context)

def results(request):
    # result_list = StudentResults.objects.all()
    # context = {'subjects': result_list}
    template = 'subjectsapp/results.html'
    return render(request,template)

templates/subjectsapp/papers_list.html
{% extends 'base.html' %}
{% load static %}


{% block containers %}

<div class="container">

    <a href="{% url 'subjectapp:add_papers' %}">ADD Papers</a>
    <p> list of Papers </p>
    <table class="table">
        <tr>
            <th>Sl no </th>
            <th>Subject name </th>
            <th>Paper type   </th>
            <th>Paper number  </th>
            <th>status  </th>
        </tr>
        {% for paper in paperslist %}
        <tr>

            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'subjectapp:edit_papertype' paper.id %}">{{ paper.id }} {{ paper.subject_name }} </a></td>
            <td>{{ paper.get_mode_display }}</td>
            <td>{{ paper.papernumber }}</td>
            <td>{{ paper.status }}</td>

        </tr>
        {% endfor %}
    </table>


</div>

{% endblock %}

templates/subjectsapp/papersadd_list.html
{% extends 'base.html' %}
{% load static %}


{% block containers %}

<div class="container">
    <h4>Add papers ...</h4>
    <form method="POST" action="{% url 'subjectapp:add_papers' %}" class="form">
         {% csrf_token %}
        {{ paperform.as_p }}
        <input type="submit" value="Submit">

    </form>

</div>

{% endblock %}

templates/subjectsapp/papersedit.html
{% extends 'base.html' %}
{% load static %}


{% block containers %}

<div class="container">

    <p>Edit</p>

    <form method="post" action="">
        {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

</div>

{% endblock %}

templates/subjectsapp/questionadd_list.html
{% extends 'base.html' %}
{% load static %}


{% block containers %}

<div class="container">
    <h4>Add Question ...</h4>
    <form method="POST" action="{% url 'subjectapp:add_questions' %}" class="form">
         {% csrf_token %}
        {{ question_form.as_p }}
        <input type="submit" value="Submit">

    </form>

</div>

{% endblock %}

templates/subjectsapp/questionedit.html
{% extends 'base.html' %}
<!--{% load static %}-->


{% block containers %}

<div class="container">

    <p>Edit</p>

    <form method="post" action="">
        {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

</div>

{% endblock %}

templates/subjectsapp/questions_list.html
{% extends 'base.html' %}
{% load static %}


{% block containers %}

<div class="container">

    <a href="{% url 'subjectapp:add_questions' %}">ADD Questions</a>
    <p> list of subjects </p>
    <table class="table">
        <tr>
            <th>Sl no </th>
            <th>Paper type</th>
            <th>question name </th>
            <th>Status  </th>
        </tr>
        {% for que in questions %}
        <tr>

            <td>{{ forloop.counter }}</td>
            <td>{{ que.papertype }}</td>
            <td>  <a href="{% url 'subjectapp:edit_questions' que.id %}">
                <div class="well">
                    Question: <b>{{ que.question_name }}</b><br>
                    A:{{ que.option1 }}<br>
                    B:{{ que.option2 }}<br>
                    C:{{ que.option3 }}<br>
                    D:{{ que.option4 }}<br>
                    ANS:{{ que.answer }}<br>

                </div>
                 </a>
            </td>
            <td>{{ que.status }}</td>

        </tr>
        {% endfor %}
    </table>


</div>

{% endblock %}

templates/subjectsapp/results.html
{% extends 'base.html' %}
{% load static %}


{% block containers %}

<div class="container">

    <a href="{% url 'subjectapp:results' %}">RESULTS</a>
    <table class="table">
        <tr>
            <th>Sl no </th>
            <th>Student name </th>
            <th>Paper type   </th>
            <th>Scored  </th>
            <th>Percentage  </th>
            <th>Result Status</th>
            <th>Date of exam</th>
        </tr>
        {% for paper in paperslist %}
        <tr>

            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>

        </tr>
        {% endfor %}
    </table><hr>


</div>

{% endblock %}

templates/subjectsapp/resultslist.html
{% extends 'base.html' %}
{% load static %}


{% block containers %}

<div class="container">

    <a href="{% url 'subjectapp:resultslist %}">resultslistgi</a>
    <p> list of subjects </p>
    <table class="table">
        <tr>
            <th>Sl no </th>
            <th>Subject name </th>
            <th>Status  </th>
        </tr>
        {% for sub in subjects %}
        <tr>

            <td></td>
            <td>  </td>
            <td></td>

        </tr>
        {% endfor %}
    </table>


</div>

{% endblock %}

templates/subjectsapp/subject_list.html
{% extends 'base.html' %}
{% load static %}


{% block containers %}

<div class="container">

    <a href="{% url 'subjectapp:add_subject' %}">ADD Subjects</a>
    <p> list of subjects </p>
    <table class="table">
        <tr>
            <th>Sl no </th>
            <th>Subject name </th>
            <th>Status  </th>
        </tr>
        {% for sub in subjects %}
        <tr>

            <td>{{ forloop.counter }}</td>
            <td>  <a href="{% url 'subjectapp:editsubject' sub.id %}"> {{ sub.subject_name }} </a></td>
            <td>{{ sub.status }}</td>

        </tr>
        {% endfor %}
    </table>


</div>

{% endblock %}

templates/subjectsapp/subjectadd_list.html
{% extends 'base.html' %}
{% load static %}


{% block containers %}

<div class="container">
    <h4>Add Subjects ...</h4>
    <form method="POST" action="{% url 'subjectapp:add_subject' %}" class="form">
         {% csrf_token %}
        {{ subform.as_p }}
        <input type="submit" value="Submit">

    </form>

</div>

{% endblock %}

templates/subjectsapp/subjectedit.html
{% extends 'base.html' %}
{% load static %}


{% block containers %}

<div class="container">

    <p>Edit</p>

    <form method="post" action="">
        {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

</div>

{% endblock %}